general_configs:
  max_num_of_fails: 2
  timeout: 10

gateway_app:
  host: "0.0.0.0"
  external_ip: "95.163.210.40"
  port: 8080
  prefix: "/api/v1"
  log_level: "info"
  reload:

  identity_serv_host: "identity-provider"
  identity_serv_port: 8090

  reservation_serv_host: "reservation-service"
  reservation_serv_port: 8070

  payment_serv_host: "payment-service"
  payment_serv_port: 8060

  loyalty_serv_host: "loyalty-service"
  loyalty_serv_port: 8050

  statistic_serv_host: "statistic-service"
  statistic_serv_port: 8040
