CREATE DATABASE IF NOT EXISTS payments;
/*GRANT ALL PRIVILEGES ON DATABASE payments TO program;*/

CREATE DATABASE IF NOT EXISTS reservations;
/*GRANT ALL PRIVILEGES ON DATABASE reservations TO program;*/

CREATE DATABASE IF NOT EXISTS loyalties;
/*GRANT ALL PRIVILEGES ON DATABASE loyalties TO program;*/