version: 16
port: 5432

default_database:
  user: program
  password: test

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi


replicaCount: 1

services:
  loyalties:
    name: loyalties
    container: cr.yandex/crpl4r9r7vin4r016c40/loyalties
    replicaCount: 1
    #env:
      # DB_DSN: "" # add on deploy like ""
    hostPort: 5432
  payments:
    name: payments
    container: cr.yandex/crpl4r9r7vin4r016c40/payments
    replicaCount: 1
    #env:
      # DB_DSN: "" # add on deploy like ""
    hostPort: 5433
  reservations:
    name: reservations
    container: cr.yandex/crpl4r9r7vin4r016c40/reservations
    replicaCount: 1
    #env:
      # DB_DSN: "" # add on deploy like ""
    hostPort: 5434
  users:
    name: users
    container: cr.yandex/crpl4r9r7vin4r016c40/users
    replicaCount: 1
    #env:
      # DB_DSN: "" # add on deploy like ""
    hostPort: 5435
  statistics:
    name: statistics
    container: cr.yandex/crpl4r9r7vin4r016c40/statistics
    replicaCount: 1
    #env:
      # DB_DSN: "" # add on deploy like ""
    hostPort: 5437