general_configs:
  max_num_of_fails: 2
  timeout: 10

postgres_db:
  user: program
  password: test
  db_name: statistics
  host: statistics
  port: 5432

loyalty_app:
  host: "0.0.0.0"
  external_ip: "95.163.210.40"
  prefix: "/api/v1/statistic"
  port: 8040
  log_level: "info"
  reload: True

